name: Test

on:
  push:
    branches-ignore:

jobs:
  code-checks:
    name: Static code check 🪲
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Typescript
        run: npm run tsc

      - name: Eslint
        run: npm run eslint
